version: '3.6'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db
  node-app:
    restart: always
    container_name: node-app
    command: ['./wait-for-it.sh', 'localhost:27017', '--', 'yarn', 'dev']
    build:
      context: '.'
      dockerfile: './node-app/Dockerfile'
    ports:
      - '7001:7001'
    links:
      - mongo
    volumes:
      - ./node-app:/opt/app/node-app
